export const mockBooks = [
  {
    id: 1,
    codigo: "L0101",
    titulo: "Dom Casmurro",
    autor: "Machado de Assis",
    descricao: "Clássico brasileiro sobre memória, ciúmes e narrativas subjetivas.",
    categoria: "Literatura Brasileira",
    genero: "Romance",
    anoPublicacao: 1899,
    paginas: 256,
    localizacao: "Estante A3",
    totalExemplares: 4,
    disponiveis: 2,
    emprestados: 2,
    capa: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 2,
    codigo: "L0102",
    titulo: "Capitães da Areia",
    autor: "Jorge Amado",
    descricao: "Retrato potente da infância marginalizada em Salvador.",
    categoria: "Literatura Brasileira",
    genero: "Drama",
    anoPublicacao: 1937,
    paginas: 288,
    localizacao: "Estante B1",
    totalExemplares: 5,
    disponiveis: 3,
    emprestados: 2,
    capa: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 3,
    codigo: "L0103",
    titulo: "O Pequeno Príncipe",
    autor: "Antoine de Saint-Exupéry",
    descricao: "Leitura sensível sobre amizade, imaginação e afeto.",
    categoria: "Infantojuvenil",
    genero: "Fábula",
    anoPublicacao: 1943,
    paginas: 96,
    localizacao: "Estante C2",
    totalExemplares: 6,
    disponiveis: 4,
    emprestados: 2,
    capa: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 4,
    codigo: "L0104",
    titulo: "Harry Potter e a Pedra Filosofal",
    autor: "J. K. Rowling",
    descricao: "Fantasia de entrada para leitores que gostam de aventura.",
    categoria: "Fantasia",
    genero: "Aventura",
    anoPublicacao: 1997,
    paginas: 264,
    localizacao: "Estante D4",
    totalExemplares: 7,
    disponiveis: 1,
    emprestados: 6,
    capa: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 5,
    codigo: "L0105",
    titulo: "Extraordinário",
    autor: "R. J. Palacio",
    descricao: "História acolhedora sobre empatia, escola e pertencimento.",
    categoria: "Juvenil",
    genero: "Ficção",
    anoPublicacao: 2012,
    paginas: 320,
    localizacao: "Estante C4",
    totalExemplares: 3,
    disponiveis: 2,
    emprestados: 1,
    capa: "https://images.unsplash.com/photo-1511108690759-009324a90311?auto=format&fit=crop&w=900&q=80",
  },
];

export const mockLoans = [
  {
    id: 1,
    titulo: "Dom Casmurro",
    codigo: "EMP-301",
    status: "ativo",
    dataEmprestimo: "20/03/2026",
    dataDevolucao: "10/04/2026",
    renovacoes: 1,
  },
  {
    id: 2,
    titulo: "O Pequeno Príncipe",
    codigo: "EMP-318",
    status: "ativo",
    dataEmprestimo: "28/03/2026",
    dataDevolucao: "12/04/2026",
    renovacoes: 0,
  },
  {
    id: 3,
    titulo: "Harry Potter e a Pedra Filosofal",
    codigo: "RES-081",
    status: "pendente",
    dataEmprestimo: "03/04/2026",
    dataDevolucao: "Aguardando retirada",
    renovacoes: 0,
  },
  {
    id: 4,
    titulo: "Extraordinário",
    codigo: "RES-084",
    status: "pendente",
    dataEmprestimo: "03/04/2026",
    dataDevolucao: "Disponível até 05/04/2026",
    renovacoes: 0,
  },
];

export const mockNotifications = [
  {
    id: 1,
    titulo: "Reserva liberada",
    descricao: "O livro Harry Potter e a Pedra Filosofal já pode ser retirado na biblioteca.",
    data: "Hoje, 09:15",
    tipo: "info",
  },
  {
    id: 2,
    titulo: "Prazo se aproximando",
    descricao: "Seu empréstimo de Dom Casmurro vence em 7 dias.",
    data: "Ontem, 17:40",
    tipo: "warning",
  },
  {
    id: 3,
    titulo: "Nova recomendação",
    descricao: "A equipe adicionou novos títulos de literatura brasileira ao acervo.",
    data: "02/04/2026",
    tipo: "success",
  },
];

export const userDashboardSummary = {
  totalLivros: 248,
  livrosDisponiveis: 187,
  meusEmprestimos: 4,
};
